config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


resources :tasks
resources :subtasks


root 'welcome#home'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :subtasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController


def index
  @subtasks = Subtask.all
end

  def new
    @subtask = Subtask.new
  end

  def create
    @subtask = Subtask.new(subtask_params)
    @subtask.save
    redirect_to '/subtasks'
    #render json: @subtask
  end

  def show
    @subtask = Subtask.find(params[:id])
  end

  def edit
    @subtask = Subtask.find(params[:id])
  end

  def update
    @subtask = Subtask.find(params[:id])
    @subtask.update(subtask_params)
    redirect_to '/subtasks'
  end


  private
  def subtask_params
    params.require(:subtask).permit(:title, :priority)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end


  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
      redirect_to '/tasks'
      #render json: @task
  end

  def show
    @task = Task.find(params[:id])

  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
      redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id]).destroy
    redirect_to '/tasks'
  end



  private
  def task_params
    params.require(:task).permit(:title)

  end




end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Todos', root_path, class:"navbar-brand", id: "logo"%>
        <!--<img alt="TodoS", src="..." >-->
      </a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodosApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">

      <%= yield %>

    </div>
  </body>
</html>

app/views/subtasks/index.html.erb
<h1>All Subtasks</h1>

<table>
  <% @subtasks.all.each do |subtask| %>
  <tr>
    <td><%= link_to subtask.title, subtask_path(subtask) %></td>
    <td><%= subtask.priority %></td>

  </tr>

  <% end %>
</table>

app/views/subtasks/new.html.erb
<h1>new subtask</h1>

<%= form_for @subtask do |subtask| %>
  <p><%= subtask.text_field :title %></p>
  <p><%= subtask.text_field :priority %></p>

  <p><%= subtask.submit %></p>
<% end %>

app/views/subtasks/show.html.erb
<p>
<%= @subtask.title %>
</p>

app/views/tasks/edit.html.erb
<h1>
  <%= form_for @task do |task| %>
    <%= task.text_field :title %>
    <%= task.submit %>
  <% end %>

</h1>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>


  <% @tasks.all.each do |task| %>
  <div class="well">
    <p><%= link_to task.title, task_path(task) %></p>
  </div>

  <% end %>

  <div class="well">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
  </div>

app/views/tasks/new.html.erb
<h1>new task</h1>

<%= form_for @task do |task| %>
  <p><%= task.text_field :title %></p>

  <p><%= task.submit %></p>
<% end %>

app/views/tasks/show.html.erb
<h1>
SHOW TASK

</h1>

<h2><%= link_to @task.title, edit_task_path(@task) %>
</h2>
<p><%= link_to 'Edit', edit_task_path(@task)%></p>
<p><%= link_to 'Delete', @task, :method => :delete, data: {confirm: "Are you sure?"} %></p>
<p><%= link_to 'All task', tasks_path %></p>

app/views/welcome/home.html.erb
<div class="jumbotron">
  <div class="center">
    <h1>Organize your Tasks</h1>

    <p><a class="btn btn-primary btn-lg" href="#" role="button">Sign Up</a></p>
  </div>

</div>